monkey/monkey

- src/mk_server.c
The usage of sigsuspend is both portable and cleaner than sleep to
indefinitely do nothing. This approach is useful in the master
loop (mk_server).
This commit closes #203
Signed-off-by: Neeraj Sharma <neeraj.sharma@alumni.iitg.ernet.in>
> Use sigsuspend instead of sleep

- mk_core/mk_utils.c
- plugins/logger/logger.c
While O_CLOEXEC is specified in POSIX.1-2008, uClibc still guards it
with _GNU_SOURCE.  So, we define _GNU_SOURCE in files where open(2)
includes O_CLOEXEC in its flags.  This fixes the build on uClibc without
affecting glibc or musl.
Signed-off-by: Anthony G. Basile <blueness@gentoo.org>
> mk_core/mk_utils.c and plugins/logger/logger.c: add _GNU_SOURCE

- include/monkey/mk_plugin.h
- mk_core/include/mk_core/mk_event.h
- mk_core/mk_event.c
- mk_core/mk_event_epoll.c
- mk_core/mk_event_kqueue.c
- mk_core/mk_event_select.c
- mk_server/mk_server.c
Issue #232 
I add new API mk_event_high_resolution_timeout_create().
Its argument is almost same as mk_event_timeout_create.
You can additionally pass nanosecond to new API.
Then you can handle more precise timer event.
Sorry , I have no idea to test new API using monkey.
So, I have tested fluent-bit.
The plugin is configured to read /proc/uptime  per 1500ms.
If correctly work, read timestamp value will increase by 1500ms.
(I have not tested on BSD.
Build error happened on FreeBSD when include ucontext.h , i will throw a patch.)
I checked symbol with string and nm command.
```
$ strings bin/fluent-bit |grep epoll
epoll_wait
epoll_ctl
epoll_create1
/home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/lib/monkey/mk_core/mk_event_epoll.c
epoll_create
epoll_ctl
epoll
$ bin/fluent-bit -i head …
```
> mk_core: event*: high resolution interval support(#232)

- plugins/fastcgi/fcgi_handler.c
we should defer the exit process ONLY if the socket is not empty.
Otherwise, the request never finish in some cases.
This fix could also apply to 1.6 branch
> fcgi: fix deferring.

- mk_server/CMakeLists.txt
- plugins/CMakeLists.txt
Cmake provides a cross-platform way to mark the build target as
platform-independent. Let's make use of this feature, in lieu of
tweaking `C_FLAGS` manually.
Main issue link: https://github.com/fluent/fluent-bit/issues/960
> build:  fix "-fpic unknown compiler option" warnings on Windows

- mk_core/mk_rconf.c
Insert a simple macro to make `mk_rconf.c` compilable on MSVC.
Also I removed <unistd.h> from the header list, since it should
be included via <mk_core/unistd.h> for portability reasons.
> core: rconf: define "PATH_MAX" macro for Windows

- mk_core/mk_rconf.c
`realpath()` function is not provided on Windows, so add ifdefs to
swtich to `_fullpath()` on MSVC. These two functions should have
the same functionality.
See: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fullpath-wfullpath
Main issue link: https://github.com/fluent/fluent-bit/issues/960
> core: rconf: use _fullpath in place of realpath on Windows

- include/monkey/mk_core/mk_macros.h
Most Windows consoles do not understand ANSI escape sequences,
and these macros leave ugly artifacts in the terminal outputs.
Let's skip them on Windows for now.
Main issue link: https://github.com/fluent/fluent-bit/issues/960
> core: macros: disable coloring on Windows for now

- include/monkey/mk_core/mk_dep_unistd.h
On Windows, we cannot use ssize_t but can actually use SSIZE_T.
This data type is probably what we need here.
> SSIZE_T: A signed version of SIZE_T.
>
> https://docs.microsoft.com/en-us/windows/desktop/winprog/windows-data-types
> core: dep_unistd: define ssize_t as SSIZE_T

- mk_core/mk_event_libevent.c
Right now `_mk_event_del()` closes sockets using `close(2)`. It does not
work on Windows, since they are implemented using the loopback
interface on localhost and we have to close them with `closecocket()`.
This patch fixes the bug by using `evutil_closesocket()`, which should
abstract the platform-specific issue away.
> core: event: fix SIGSEGV on cancelling events on Windows

- include/monkey/mk_core/mk_event.h
Previously the downstream programs had to figure out the correct
function to close sockets depending on the backend library in use.
(i.e. use evutil_socketclose if the mk_core's backend is libevent)
Failing to do so would result in segmentation faults and it was
somewhat cumbersome. With this patch library users can now call
mk_event_closesocket() to close sockets safely.
Part of: fluent/fluent-bit/issues/960
> core: event: introduce mk_event_closesocket() function

- mk_core/mk_event_libevent.c
A timeval struct is a pair of {sec, usec}, so we need to convert
the wait interval (which is in nanoseconds) to microseconds before
assigning to tv_usec.
This fixes the bug that mk_event_timeout_create() sometimes never
timeouts on Windows.
Part of fluent/fluent-bit/issues/960
> core: event: handle nanoseconds properly in the libevent backend

- mk_core/external/winpthreads.c
When pthread_key_create() generates the first TSD key, it fails
to initialize the first slot of _pthread_key_dest properly. For
this reason, the subsequent call for the method can generate an
invalid TSD key.
This was the root cause of fluent-bit randomly failing with
segmentation fault. Fix it.
> core: winpthreads: fix segfaults on pthread_set_specific()

- mk_core/mk_rconf.c
This enables you to do this on Windows:
@INCLUDE input_*.conf
Since Windows does not provide glob(3), we needed to implement
the equivalent using FindFirstFile(). This implements that, and
should make wildcard paths (including nested ones) just work.
This is an awaited feature requested by several Windows users;
See fluent/fluent-bit/issues/1692 for the backround.
> core: implement mk_rconf_read_glob() for Windows

- mk_core/CMakeLists.txt
- mk_core/mk_file.c
The implication of this patch is that the modules in Fluent Bit that
rely on `mk_file_to_buffer()` now can be compiled and linked on Windows.
> core: file: make mk_file.c compilable on Windows

- mk_core/mk_rconf.c
Justin Angra pointed out that these strcat() have a potential overrun
bug. His observation is correct. In particular, when the input string
`path` is very long, it can overrun the buffer while appending `p1`.
This patch fixes the issue by using a safer variant (strcat_s), and
check the return code explicitly.
> mk_core: mk_rconf: Fix potential overrun in mk_rconf_read_glob()

- mk_core/deps/libevent/cmake/VersionViaGit.cmake
libevent's CMakeLists.txt is buggy. In particular, when an
annotated tag is attached to a commit, the build process crashes.
For example, if we do:
% cd fluent-bit/build/
% git tag -a v1.5
% cmake ..
% cmake --build .
... it results in the following error:
event-config.h(14): error C2001: newline in constant
Luckly this bug is already fixed in the upstream project. This
ports the relevant fix to mk_core/deps/libevent.
Link: https://github.com/libevent/libevent/commit/a9aa2b36
LInk: https://github.com/libevent/libevent/commit/d65e3e1d
Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>
> monkey: libevent: import version detection fix from libevent

- include/monkey/mk_scheduler.h
- mk_server/mk_scheduler.c
When Monkey detects a broken connection (not necessarily an error;
just a closed connection for most cases), it tries to purge all the
HTTP sessions in the worker.
This is dangerous because a HTTP worker can process several requests
concurrently, so the cleanup effort can inadvertently drop other
non-broken connections:
+--------+
|        |--[ REQ1 ] -> <CLOSED> -> mk_sched_threads_destroy_all()
| WORKER |                               |
|        |--[ REQ2 ] <-------------------+
+--------+
In such case, a concurrent connection (REQ2 in the above diagram) will
exit abruptly while processing, causing its client to emit "unexpected
EOF" error.
This patch possibly fixes the bug "Fluent Bit is sometimes mis-detected
as crashed due to random broken responses".
Signed-off-by: Fujimoto Seiji …
> server: scheduler: Do not drop other HTTP connections on network error

- mk_core/mk_rconf.c
This PR tries to address the issue from https://github.com/fluent/fluent-bit/issues/3162
where the invalid configuration file will not populate a non-zero code:
```
$ cat fluent-bit.conf
[INPUT]
Name cpu
[OUTPUT]
Name stdout
NONSENSE NONSENSE NONSENSE
$ bin/fluent-bit -c fluent-bit.conf --dry-run
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io
[2021/03/08 16:33:03] [  Error] File fluent-bit.conf
[2021/03/08 16:33:03] [  Error] Error in line 7: Invalid indentation level
configuration test is successful
$ echo $?
0
```
This PR fixes the issue and below is the new output:
```
$ bin/fluent-bit -c fluent-bit.conf --dry-run
Fluent Bit v1.8.0
* …
```
> core: rconf: fixes incorrect skipping of configuration parse error

- deps/regex/CMakeLists.txt
- include/monkey/mk_core/external/winuio.h
- include/monkey/mk_core/mk_iov.h
- include/monkey/mk_core/mk_uio.h
- include/monkey/mk_fifo.h
- include/monkey/mk_http_internal.h
- mk_core/mk_iov.c
- mk_server/mk_fifo.c
- mk_server/mk_scheduler.c
mk_core : Changed the iovec structure definition name to mk_iovec to avoid issues with the definition made by msgpack (only when having to plug it in windows)
mk_fifo : Fixed a bug in the fifo channel array definition which was defined as a 2
default size integer array (32 bits) which works for most platforms but libevent which defines the socket type as either a 32 bit int for 32 bit platforms or a 64 bit int for 64 bit platforms resulting in the second peer of the pipe pair being written outside of the array bounds causing both a memory corruption issue as well as a connectivity issue.
regex: Since the regex engine change was made on all platforms the regex engine compilation shouldn't be dependent of if the target platform does have a regex implementation or not
> Compatibility fix for fluent-bit + Functionality fix in fifo channels

- api/test.c
- deps/regex/re.h
regex: incremented the symbol limit in the regex engine so it properly compiles longer expressions, otherwise it compiles the regex up to the symbol limit stopping there but not failing which causes false positives.
api_test: added two handlers to test the regex engine
TODO: refactor tinyregex so the regex structure is dynamically allocated making it flexible, less wasteful and more communicative (raising errors!)
> regex: engine symbol limit incremented

- mk_server/mk_http_parser.c
http_parser : Changed the parsing logic of the first line of the request to be able to handle unescaped spaces in query string arguments by looking for the line end character and then going back to the previous space instead of looking for the first space after the question mark is found.
> http_parser : Fixed bug in the parse logic of the first line of the request.

- mk_server/monkey.c
Fixes #342.
We should send MK_SCHED_SIGNAL_FREE_ALL signal  to workers.
I modified to use mk_sched_broadcast_signal for broadcasting.
> core: broadcast FREE_ALL signal on exit(#342)

- include/monkey/mk_lib.h
- include/monkey/mk_vhost.h
- mk_server/mk_lib.c
- mk_server/mk_vhost.c
https://github.com/fluent/fluent-bit using monkey as a library and it uses vhost api.
We need to release vhost on exit service and I sent a patch to add the function to release vhost.
Note: https://github.com/fluent/fluent-bit/pull/3489
- expose `mk_vhost_lookup` to use from `mk_vhost_destroy`.
- add `mk_vhost_destroy(struct mk_vhost *)`
-  The implementation is based `mk_vhost_free_all`. `mk_vhost_free_all` is to release vhost iteratively.
- I moved the implementation from `mk_vhost_free_all`. (This diff is confusing, but It just be moved and add NULL checking)
This is an output of fluent-bit.
There is still leakage but some leaks caused by vhost are removed. https://github.com/fluent/fluent-bit/pull/3489#issue-645135979
```
$ valgrind --leak-check=full bin/fluent-bit -i cpu -o …
```
> Add `mk_vhost_destroy` function to release vhost

- include/monkey/mk_core/mk_event.h
- mk_core/mk_event.c
- mk_core/mk_event_epoll.c
- mk_core/mk_event_kqueue.c
- mk_core/mk_event_libevent.c
- mk_core/mk_event_select.c
This pull request adds the mk_event_timeout_disable function meant to remove a timer from the event loop thus properly preventing any non timely timer ticks from generating events.
> core: event: introduce mk_event_timeout_disable() function

- include/monkey/mk_core/mk_event_epoll.h
- include/monkey/mk_core/mk_event_kqueue.h
- include/monkey/mk_core/mk_event_libevent.h
- include/monkey/mk_core/mk_event_select.h
Out of bounds read when evl->n_events is equal to the number of event slots the event loop was initialized with.
This out of bounds read should not cause any issues itself unless the mk_event_ctx structure is perfectly aligned at the end of the page with no contiguously mapped page or with a mapped page that lacks the PROT_READ protection mode in which case it would cause a segmentation fault.
> core: event: fixed out of bounds memory read

- mk_core/mk_rconf.c
This extends the verification logic for indentation, so that
users can distinguish the following three failure modes.
[INPUT]
Name dummy
Tag 1
=> (1) Indentation level is too low
[INPUT]
Name dummy
\tTag 1
=> (2) Incositent use of tab and space
[INPUT]
Name dummy
Tag 1
=> (3) Extra indentation level found
Especially (2) was somewhat difficult for users to recognize what
is wrong, because a) indentation looks fine on text editor, b) but
Fluent Bit is still complaining.
> mk_core: mk_rconf: Be more verbose on indentation errors

- mk_server/mk_http.c
This PR adds a simple initialization check to the mk_http_error function so when it's 
called from mk_http_parser when fluent-bit is trying to process a user request in the
in_http plugin which does not initialize the monkey server (at all) it does not try to
deliver the error message itself but rather leave it to the caller.
This could also be implemented by adding an explicit initialization flag to the mk_server 
structure, in this case we rely on the fact that we know that if workers is zero it has not
been initialized.
Signed-off-by: Leonardo Alminana <leonardo@calyptia.com>
> core: added rudimentary initialization check on mk_http_error

- include/monkey/mk_http_parser.h
This PR increase custom http headers to reasonable count. For example, cloudflare adds to requests another 5 custom CF-* headers.
> increase custom http headers count

- api/test.c
- mk_core/mk_iov.c
- plugins/cgi/cgi.c
- plugins/dirlisting/dirlisting.c
- plugins/fastcgi/fcgi_handler.c
- plugins/liana/liana.c
Resolve various compiler warnings:
1. unused variables
2. incompatible pointer assignment
3. implicit function declaration
Fixes #344 (I think).
cc @edsiper
> Fix compiler warnings

- mk_core/mk_rconf.c
fixes https://github.com/fluent/fluent-bit/issues/1294
Currently, using `@INCLUDE` with glob + absolute path fails with "glob: no match".
These fail with an error.
```
@INCLUDE /fluent-bit/etc/test/*.conf
@INCLUDE /fluent-bit/../fluent-bit/etc/test/*.conf
@INCLUDE /fluent-bit/*/*/*.conf
```
Glob with relative path or absolute path without glob works.
```
@INCLUDE /fluent-bit/etc/test/test.conf
@INCLUDE test/test.conf
@INCLUDE /fluent-bit/../fluent-bit/etc/test/test.conf
@INCLUDE ../etc/test/test.conf
@INCLUDE ../etc/test/*.conf
@INCLUDE test/*.conf
@INCLUDE **/*.conf
```
It is not working because even absolute path is passed, `conf->root_path` is concatenated for `glb_path`.
This PR handles absolute path with glob as is.
Also, adds a more helpful warning message.
Tested with various …
> core: Fix abosolute glob

- mk_server/mk_clock.c
- mk_server/mk_fifo.c
- mk_server/mk_lib.c
- mk_server/mk_server.c
This PR makes a few changes required for monkey to be able to terminate when requested : 
1. Makes the clock thread immediately cancellable (this could be a quirk in winpthreads)
2. Makes mk_server_loop_balancer monitor the management channel waiting for a termination request (otherwise it's an infinite loop)
3. Fixes incompatible IO api usage in a few places (in windows we're using libevent which uses sockets for pipes which means we can't use read/write and we have to use recv/send and it also affects the fd close function)
Notes: The ifdef blocks for these IO functions aren't elegant to say the least so a future PR will abstract that and hopefully the data type used for socket file descriptors because libevent represents sockets as intptr_t which is 64 bits wide in x64.
> core: windows shutdown issue corrections

- include/monkey/mk_core/mk_list.h
Signed-off-by: Matthew Fala <falamatt@amazon.com>
It seems that there is a reference bug in the mk_list_add_after() function which is used in mk_header.c.
```
+--------+--------+
| prev =>|<= next |
+--------+--------+
+--------+--------+-------+
| prev =>|<=_new=>| * next|
+---|----+--------+-|-----+
^---------------<  (broken reference) 
```
```
+--------+--------+-------+
| prev =>|<=_new=>|<=next |
+--------+--------+-------+
```
> list: fix add_after prev pointer reference bug

- include/monkey/mk_stream.h
- mk_server/mk_stream.c
Added `mk_channel_release` which was missing and is required to prevent a memory leak in fluent-bit.
Signed-off-by: Leonardo Alminana <leonardo@calyptia.com>
> server: channel: added cleanup routine

- mk_server/mk_scheduler.c
Fix a missing-unlocking bug in mk_scheduler.c
> Fix a missing-unlocking bug

- mk_core/mk_rconf.c
Signed-off-by: Matthew Fala <falamatt@amazon.com>
On exiting a program due to invalid indentation, monkey throws a malloc free error.
It appears key and value are freed before they are allocated, causing this error.
Deleting the unnecessary frees resolves the problem
This is really an upstream monkey error: https://github.com/monkey/monkey/blob/master/mk_core/mk_rconf.c#L366 .
Please feel free to reject this PR and resolve in Monkey if that would be standard procedure.
Config file causing malloc free error:
```
[SERVICE]
Grace 30
Log_Level debug
[INPUT]
Name http
host 0.0.0.0
port 8888
[OUTPUT]
Name stdout
Match *
```
----
Enter `[N/A]` in the box, if an item is not applicable to your change.
**Testing**
Before we can approve your change; please submit the following in a comment:
- [X ] …
> mkcore: resolve monkey indentation sentinel termination error

- mk_core/mk_event_kqueue.c
When using NOTE_SECONDS side of EV_SET routine on macOS,
we got a severe performance degradation on threaded input plugin
environment.
Instead, we shouldn't use NOTE_SECONDS event filtering flag and
specify as milliseconds on macOS.
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>
> core: event: kqueue: Don't use NOTE_SECONDS on macOS

- include/monkey/mk_core/mk_list.h
Fluent-bit project uses monkey as a library.
This patch is to add `mk_list_add_before` to fix a bug of fluent-bit.
https://github.com/fluent/fluent-bit/pull/5590
I found that there is no way to add entry like below case.
1. head
2. head -> val1
3. head -> val2 -> val1
A point is 3, there is no API.
1. mk_list_init(&head)
2. mk_list_add(&val, &head)
3.  ??? 
We can't use `mk_list_add_after(&val2, &head, &head)` since `head->next` and `head->prev` is same value `val1`.
Then it calls `mk_list_add` the list will be `head->val1->val2`
https://github.com/monkey/monkey/blob/992749ec1e8e2bc5b8cbcf1cf4fde67d297354cc/include/monkey/mk_core/mk_list.h#L73
> list: add mk_list_add_before

- .github/workflows/build-pr.yaml
- CMakeLists.txt
- include/monkey/mk_core.h
- include/monkey/mk_core/mk_dirent.h
- include/monkey/mk_core/mk_getopt.h
- include/monkey/mk_core/mk_pipe.h
- include/monkey/mk_core/mk_pthread.h
- include/monkey/mk_core/mk_sleep.h
- include/monkey/mk_core/mk_string.h
- include/monkey/mk_core/mk_uio.h
- include/monkey/mk_core/mk_unistd.h
- include/monkey/mk_core/mk_utils.h
- mk_core/CMakeLists.txt
- mk_core/mk_event_libevent.c
core: removed TLS usage from a macro that doesn't need it because it caused a memory corruption in certain cases
where a web server instance was not created (mostly test cases but I think running fluent-bit with http_server disabled could cause the same issue)
core: event: libevent: fixed the timer destruction order so we wouldn't try to remove an already closed socket from the event loop
build: fixed the mk_core_info.h generation and inclusion paths (as well as the directives)
Everything was tested in stand alone mode as well as inside fluent-bit with no changes required for it to build and work in either mode.
> core and build fixes

- include/monkey/mk_core/mk_event.h
- mk_core/mk_event.c
- mk_core/mk_event_epoll.c
- mk_core/mk_event_kqueue.c
- mk_core/mk_event_libevent.c
- mk_core/mk_event_select.c
Add a new function mk_event_channel_destroy which destroys channels created by mk_event_channel_create as well as closing the file descriptors it opened.
> core: event: add mk_event_channel_destroy function for mk_event_chanel_create.

- mk_core/mk_event_kqueue.c
This is because `struct mk_event *event;` variable is not initialized yet before checking MK_EVENT_IS_REGISTERED macro.
It shouldn't put before `event` variable initalization.
When swap the places of cast from void* and the macro, this issue should be solved.
This issue is only occurred on teardown.
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>
> mk_core: Fix always invaild value on if clause at _mk_event_timeout_destroy

- mk_server/mk_server.c
Closes #382 
`mk_server_listen_exit` previously used `close` to close the server file descriptor. On Windows it needs to be `closesocket`. This PR switches that function to use the cross-platform `mk_event_closesocket`.
Signed-off-by: braydonk <braydonk@google.com>
> server: use cross platform socket close

- mk_core/mk_event_libevent.c
When destroying the timeout, we need to close the socket associated with the event manually so that the cb_timeout eventually fails to write data and cleans itself up.
Second proposed solution to #390, will close if #391 is chosen.
> mk_core: manually close socket in timeout destroy

- mk_core/mk_string.c
Note: this function returned an invalid pointer to released memory
> core: removed alloca calls from the memmem replacement function

- mk_core/mk_event_epoll.c
- mk_core/mk_event_kqueue.c
- mk_core/mk_event_libevent.c
- mk_core/mk_event_select.c
- mk_server/mk_fifo.c
- mk_server/mk_net.c
> Note to the reviewer: This change requires from now on that when creating an event in memory, `MK_EVENT_ZERO()` is called or else a segfault on `mk_event_add()` will occur.
Currently if an event is added to the event loop twice, an error can occur where the ready list (priority list) is corrupted, as the link list in the event is zeroed.
Since mk_event may be uninitialized memory, we have no way of tracking whether the event has been added to the loop before
~~## Solution
Require that MK_EVENT_ZERO is always called before the mk_event_add() function is called. Then we know if we should remove records of the event from the loop before adding again.~~
~~## Honest Comments~~
~~Honestly, I'm not a huge fan of this solution, as it means that if we forget to zero an mk_event after creating …
> eventloop: zero priority linked list on init

- test/CMakeLists.txt
- test/event_timeout.c
- test/lib_server.c
Adding a test to cover the fix in #390 on Linux.
> test: event timeout test for Linux

- mk_core/mk_event_epoll.c
Fix error:
"Uninitialised value was created by a stack allocation" at `_mk_event_add`
Addresses: #399
> mk_event_epoll: fix uninitialised value

- mk_core/mk_utils.c
MK_MAX_PID_LEN is max amount of pid digits, not including the null terminator.
> core: utils: fix off-by-one error when defining length of pidstr

- mk_core/external/winpthreads.c
Without this patch values with a key equal to the maximum will not be set and will return NULL when calling `pthread_getspecific`.
> winpthreads: fix off by one bug in pthread_setspecific which impedes setting values

- mk_server/mk_http_thread.c
Fixes #411 by cleaning up the `mk_http_thread_libco_params` pointer in mk_http_thread_destroy.
> HTTP: fix libco params thread memory leak

- plugins/logger/logger.c
Apologies for opening an issue on a very old CVE, do feel free to close as unwanted.
We are currently doing a CVE triage for Yocto and found that CVE-2013-1771 still applies to the current version.
I couldn’t find a trace that this CVE report ever made it to this project, and I thought while I’m in here, I’ll offer a fix, if it is wanted.
The original description can be found here: https://www.openwall.com/lists/oss-security/2013/02/26/10
If this gets merged, I’m also happy to notify NIST to update https://nvd.nist.gov/vuln/detail/CVE-2013-1771 with the future fix version.
Again, if this is not desired, do feel free to close with or without comment, no hard feelings :)
> fix: set log file permissions to 0600, closes CVE-2013-1771

- mk_core/mk_event_select.c
Fixes a type error introduced in #359:
```
…/mk_core/mk_event_select.c:370:34: error: invalid type argument of '->' (have 'struct mk_event')
370 |             if (ctx->fired[index]->fd == event->fd) {
|                                  ^~
…/mk_core/mk_event_select.c:378:34: error: incompatible types when assigning to type 'struct mk_event' from type 'struct mk_event *'
378 |     ctx->fired[loop->n_events] = event;
|                                  ^~~~~
```
> core: event: Fix typo in mk_event_select.c.

- api/test.c
- include/monkey/mk_http_parser.h
- mk_server/mk_http.c
- mk_server/mk_http_parser.c
When requests arrives through a POST or PUT method and uses `chunked` transfer-encoding, the parser was not allowing or processing the payload.
This patch extends the parser to support chunked transfer encoding allowing the parser not to fail and validate the chunks that arrives.
It also provides some new helpers functions to decode and extract the content in a new memory buffer. New functions available:
__1. mk_http_parser_content_length()__
Indicate the content length of the payload, if content-length has been set in the headers it will return that length (after being validated). If the request came with chunked transfer encoding, it will return the total size of the chunks without including the chunked headers and `\r\n` marks.
```c
size_t mk_http_parser_content_length(struct …
```
> server: add support for transfer chunked encoding

- include/monkey/mk_core/external/winuio.h
- include/monkey/mk_core/mk_dep_unistd.h
During debugging on weird compilation failures, I found two issues for potential compilation errors on MSVC.
Currently, it was concealed implicitly but once we'll include flb_mem.h in another place from the ordinary ones, the following errors are generated:
```
flb_simdutf_connector.cpp
D:\a\fluent-bit\fluent-bit\lib\monkey\include\monkey\mk_core\external/winuio.h(39): error C2664: 'int send(SOCKET,const char *,int,int)': cannot convert argument 2 from 'void *const ' to 'const char *'
D:\a\fluent-bit\fluent-bit\lib\monkey\include\monkey\mk_core\external/winuio.h(39): note: Conversion from 'void*' to pointer to non-'void' requires an explicit cast
C:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\um\winsock2.h(2085): note: see declaration of 'send' …
```
> core: winuio: Fix send function arguments type glitch and include stdint.h if available on MSVC
